version: '3.5'
services:
  api:
    container_name: nodeAPI
    build: .
    external_links:
      - "maxidan-db"
    networks:
      - maxidan
networks:
  maxidan:
    external:
      name: maxidan_network

